package com.binarystudio.academy.slidez.app.session;

public enum SessionResponseCodes {

	NO_SESSION_WITH_SUCH_LINK, COULD_NOT_ADD_SESSION, COULD_NOT_LOAD_SNAPSHOT, COULD_NOT_START_POLL, COULD_NOT_ANSWER_POLL, COULD_NOT_START_QUIZ, COULD_NOT_ANSWER_QUIZ, COULD_NOT_START_QA_SESSION

}
