package com.binarystudio.academy.slidez.domain.session.enums;

public enum ResponseType {

	SNAPSHOT, ANSWERED_POLL, STARTED_POLL, STARTED_QUIZ, ANSWERED_QUIZ, STARTED_QA_SESSION, ASKED_QUESTION, ADDED_REACTION, LIKED_QUESTION, SET_QUESTION_VISIBILITY

}
