name: CI-CD-AWS-Beanstalk

env:
  AWS_EB_S3_BUCKET: "bsa.slidez-core-builds"
  EB_APPLICATION_NAME: "bsa-2021-slidez-core"
  EB_ENVIRONMENT_NAME: "Bsa2021slidezcore-env"
  DEPLOY_PACKAGE_NAME: "slidez-app-build.zip"
  AWS_REGION_NAME: "eu-west-1"
  AWS_SPA_S3_BUCKET: "bsa.slidez-fe-spa"

on:
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy-core:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Clone code from repository
        uses: actions/checkout@v2
        
      - name: Create ZIP deployment package
        working-directory: slidez-core
        run : zip -r ../${{ env.DEPLOY_PACKAGE_NAME }} *
           
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: ${{ env.AWS_REGION_NAME }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          version_label: "v-${{ github.sha }}"
          deployment_package: "./${{ env.DEPLOY_PACKAGE_NAME }}"
          
      - name: Successful build
        run : echo "Build successful!"
  
  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone code from repository
        uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
           aws-region: ${{ env.AWS_REGION_NAME }}
           
      - name: Build frontend
        working-directory: slidez-fe-core
        run : |
          yarn install --frozen-lockfile && yarn build \
          aws s3 sync --cache-control 'max-age=604800' --exclude index.html build/ s3://${{ env.AWS_SPA_S3_BUCKET }}/; \
          aws s3 sync --cache-control 'no-cache' build/ s3://${{ env.AWS_SPA_S3_BUCKET }}/; \
          
      
      - name: Successful build
        run : echo "Build successful!"
      
