name: CI-CD-AWS-Beanstalk

env:
  AWS_EB_S3_BUCKET: "bsa.slidez-core-builds"
  EB_APPLICATION_NAME: "bsa-2021-slidez-core"
  EB_ENVIRONMENT_NAME: "Bsa2021slidezcore-env"
  DEPLOY_PACKAGE_NAME: "slidez-app-${{ github.sha }}-core.zip"
  AWS_REGION_NAME: "eu-west-1"
  AWS_SPA_S3_BUCKET: "bsa.slidez-fe-spa"

on:
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code from repository
        uses: actions/checkout@v2
        
      - name: Create ZIP deployment package
        run : |
          cd slidez-core; \
          zip -r ../${{ env.DEPLOY_PACKAGE_NAME }} *; \
          cd ..;
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
           aws-region: ${{ env.AWS_REGION_NAME }}
       
      - name: Copy package to S3
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.AWS_EB_S3_BUCKET }}
      
      - name: Successful build
        run : echo "Build successful!"
    
  deploy-core:
    runs-on: ubuntu-latest
    needs: [ build-core ]
    
    steps: 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
           aws-region: ${{ env.AWS_REGION_NAME }}
      
      - name: Create ElasticBeanstalk app version
        run : | 
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --source-bundle S3Bucket="${{ env.AWS_EB_S3_BUCKET }}",S3Key="${{env.DEPLOY_PACKAGE_NAME}}" \
          --version-label "v-${{ github.sha }}" \
          --description "Automatic deplayment from github actions. SHA-${{ github.sha }}"
        
      - name: Update ElasticBeanstalk environment
        run: |
          aws elasticbeanstalk update-environment \
          --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
          --version-label "v-${{ github.sha }}"
        
      - name: Successful build
        run : echo "Build successful!"
  
  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
           aws-region: ${{ env.AWS_REGION_NAME }}
      - name: Build frontend
        run : |
          cd slidez-fe-core; \
          npm ci && npm run build; \
          aws s3 sync --cache-control 'max-age=604800' --exclude index.html build/ s3://${{ env.AWS_SPA_S3_BUCKET }}/; \
          aws s3 sync --cache-control 'no-cache' build/ s3://${{ env.AWS_SPA_S3_BUCKET }}/; \
          cd ..;
      
